version: "3"
services:
  web:
    env_file:
        - .env
    image: api
    depends_on:
        - db
        - webnet
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  db:
    env_file:
        - .env
    image: postgres:latest
    depends_on:
        - webnet
    volumes:
        - pgdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:

volumes:
    pgdata:
